<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>TShock_Map</RootNamespace>
    <AssemblyName>Map_TShock</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="7.0.0" /> <!-- Adjust version as needed -->
    <Reference Include="OTAPI">
      <HintPath>..\..\tshock_4.3.24\OTAPI.dll</HintPath>
    </Reference>
    <Reference Include="TerrariaServer">
      <HintPath>..\..\tshock_4.3.24\TerrariaServer.exe</HintPath>
    </Reference>
    <Reference Include="TShockAPI">
      <HintPath>..\..\tshock_4.3.24\ServerPlugins\TShockAPI.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="AfterBuild" AfterTargets="Build">
    <Copy SourceFiles="$(TargetDir)$(TargetName).dll" DestinationFolder="$(SolutionDir)..\tshock_5.2\ServerPlugins" />
  </Target>

</Project>
